config/routes.rb
Rails.application.routes.draw do

  namespace :comments do
    get 'archives/index'
  end
  get 'comments/create'
  ActiveAdmin.routes(self)
  devise_for :users

  root to: 'entries#index'

  namespace :entries do
    resources :archives, only: [:index, :update]
  end

  namespace :comments do
    resources :archives, only: [:index, :update]
  end

  resources :entries, only: [:index, :show, :create, :update] do
    resources :attachments, only: [:create]
  end

  namespace :users do
    resources :pendings, only: [:index, :update]
  end

  resources :circles, only: [:index, :show, :create, :update]
  resources :users, only: [:index, :show, :update]
  resources :documents, only: [:index, :create]

  get 'comments/:id/bee', to: 'entries#bee', as: 'bee'
  post '/entries/:id/comments', to: 'comments#create', as: 'create_comment'
  get 'entries/:id/bookmark', to: 'entries#bookmark', as: 'bookmark'

  get 'bookmarks', to: 'entries#my_bookmarks', as: 'my_bookmarks'
  get 'dates', to: 'entries#dates', as: 'dates'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entries
  has_many :comments, dependent: :destroy
  has_many :bees, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :attachments
  belongs_to :school

  enum role: { super_admin: 0, admin: 1, mitglied: 2, beobachter: 3 }

  mount_uploader :pic, ProfileUploader
end

app/controllers/users/pendings_controller.rb
class Users::PendingsController < ApplicationController
  def index
    @pending_users = policy_scope([:pending, User.where(approved: false)])
    if current_user.mitglied? && current_user.approved
      redirect_to user_path(current_user), notice: 'Your Account has already been approved!'
    end
  end

  def update
    @pending_user = User.find(params[:id])
    @pending_user.approved = true
    authorize([:pending, @pending_user])
    if @pending_user.save
      redirect_to users_pendings_path
      flash[:notice] = "User #{@pending_user.first_name} has been approved!"
    else
      redirect_to users_pendings_path
      flash[:alert] =  "Something went wrong..."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = policy_scope(User)
    unless current_user.admin? || current_user.super_admin?
      redirect_to entries_path, alert: 'Fehlende Admin-Rechte.'
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    if current_user.admin? || current_user.super_admin?
      @user = User.find(params[:id])
      @user.role = edit_user_params[:role].to_i
      authorize @user
      if edit_user_params[:role].to_i == 0  && !current_user.super_admin?
        redirect_to users_path, alert: "You don't have this permission."
      else
        if @user.save
          redirect_to user_path(@user), notice: "Erfolgreich geändert: #{@user.first_name} ist #{@user.role}."
        else
          redirect_to user_path(@user), alert: "Wurde nicht geändert."
        end
      end
    else
      redirect_to user_path(@user), alert: "Fehlende Admin-Rechte."
    end
  end

  private

  def edit_user_params
    params.require(:user).permit(:role)
  end
end

app/views/users/pendings/index.html.erb
<div class="container margin-top-30 users-list">
  <% @pending_users.each do |user| %>

    <%= link_to '#' do  %>
      <div class="author-infos big list-item justify-content-between pr-2">
        <div class="items-left d-flex align-items-center">
          <div class="avatar avatar-medium" id="author-pic" style="background-image: url(<%= asset_path 'profile.png' %>);">
          </div>
          <div>
            <h3 class="red-font bold-font"><%= user.first_name %> <%= user.second_name %> |  Status: <%= user.approved ? "approved!" : "Pending" %></h3>
            <h3><%= user.role %></h3>
          </div>
        </div>
        <%= button_to 'Approve', users_pending_path(user), class: 'btn-pending', data: { confirm: "Approve #{user.first_name}?" },  method: :patch %>
      </div>
    <% end %>
  <% end %>
</div>